### ISSUE TITLE
RunE2ETest function does not return terraform outputs 

### ISSUE THREAD

**Issue by kevball2** [Azure/terraform-module-test-helper#91]
I have tried adding assertions as show in the readme sample but the output from the `terraform_module_test_help.TerraformOutput`  is returned empty. 

Here is the function call I am trying
``` golang
func TestExample(t *testing.T) {
	dir := filepath.Join("../", "examples")
	if _, err := os.Stat(dir); os.IsNotExist(err) {
		t.Fatalf("Directory %s does not exist", dir)
	}
	files, err := os.ReadDir(dir)
	if err != nil {

		log.Fatal(err)
	}
	for _, file := range files {
		if file.IsDir() {
			file.Info()
			t.Run(file.Name(), func(t *testing.T) {
				terraform_module_test_helper.RunE2ETest(t, "../", filepath.Join("examples", file.Name()), terraform.Options{},
					func(t *testing.T, output terraform_module_test_helper.TerraformOutput) {
						resourceGroupName, ok := output["name"].(string)
						fmt.Println("Name of the resource Group:" + resourceGroupName)
						fmt.Println(output["name"].(string))
						fmt.Println(output["resource"].(string))
						fmt.Println(output["resource_id"].(string))
						assert.True(t, ok)
						assert.Regexp(t, regexp.MustCompile("/subscriptions/.+/resourceGroups/"), resourceGroupName)
					})
			})
		}
	}
}
```
Just wanted to confirm if the outputs portion should be working or not.

**Comment by lonegunmanb** [comment]
Hi @kevball2 thanks for reporting this issue to us. This helper callback SHOULD return outputs as you expected, we have an [unit test](https://github.com/Azure/terraform-module-test-helper/blob/main/e2etest_test.go#L15-L23) to verify this.

Would you please share your code repository with us so we can try to reproduce this issue? Thanks!

**Comment by kevball2** [comment]
@lonegunmanb,  Here is the repo I have been testing with - https://github.com/kevball2/terraform-azurerm-avm-res-resource-resourcegroup/tree/feat-resourcegroup-add

I created unit test samples to show the issue, `TestUnitExampleTest` and `TestUnitExampleTestFail`

I am running the tests with the following commands: 

```golang
go test -v -timeout=720m -run TestUnitExampleTest
go test -v -timeout=720m -run TestUnitExampleTestFail
```

The failing test passes a function with assertions but I get no output back from the run (at least when I tried to debug the test). 
I see the same issue if I run the `RunE2Etest` function as well.

**Comment by kevball2** [comment]
@lonegunmanb I sorted my issue, I didn't have the appropriate outputs.tf created for my tests. I did run into another issue (terratest related) trying to get the assertion checks to run against other clouds (AzureUSGovernment) the resources deploy but when I use a built in assertion `exists := azure.ResourceGroupExists(t, resourceGroupName, subscriptionID)` it fails to find the subscription (guessing I have to set tenantId and or cloud someplace. 

There are constants on the Azure Go Package (https://pkg.go.dev/github.com/gruntwork-io/terratest@v0.46.11/modules/azure#pkg-constants) I am unsure how to set them though.

**Comment by lonegunmanb** [comment]
Interesting @kevball2, I never realized that `terratest` do have this `azure` sub module to query the resource's status. I've checked it's [code](https://github.com/gruntwork-io/terratest/blob/master/modules/azure/authorizer.go#L11-L28), I guess we have three different approaches to get this authorizer work for you:

1. [Auth with Azure CLI](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli)
2. [Auth with Client Credentials](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret)
3. Auth with a file stored in env `AZURE_AUTH_LOCATION` which contains credentials like approach 2.

If you want to test with Azure USGovernment cloud, you might need to set env `AZURE_ENVIRONMENT` to `AzureUSGovernmentCloud`, see [here](https://github.com/gruntwork-io/terratest/blob/master/modules/azure/client_factory_test.go#L18) and [here](https://github.com/gruntwork-io/terratest/blob/master/modules/azure/client_factory.go#L48)

I would suggest you search or open an issue on TerraTest's repo, please let me know if you have any further question about this library. Thanks.

**Comment by kevball2** [comment]
Thanks for the for all the help @lonegunmanb 

I got a good test now to work from
```golang

import (
	"log"
	"os"
	"path/filepath"
	"testing"

	terraform_module_test_helper "github.com/Azure/terraform-module-test-helper"
	"github.com/gruntwork-io/terratest/modules/azure"
	"github.com/gruntwork-io/terratest/modules/terraform"
	"github.com/stretchr/testify/assert"
)

func UnitTestResourceGroupExists(t *testing.T) {
	dir := filepath.Join("../", "examples")
	if _, err := os.Stat(dir); os.IsNotExist(err) {
		t.Fatalf("Directory %s does not exist", dir)
	}
	files, err := os.ReadDir(dir)
	if err != nil {

		log.Fatal(err)
	}
	for _, file := range files {
		if file.IsDir() {
			file.Info()
			t.Run(file.Name(), func(t *testing.T) {
				terraform_module_test_helper.RunE2ETest(t, "../", filepath.Join("examples", file.Name()), terraform.Options{},
					func(t *testing.T, output terraform_module_test_helper.TerraformOutput) {
						resourceGroupName, ok := output["name"].(string)
						subscriptionID := os.Getenv("ARM_SUBSCRIPTION_ID")
						assert.True(t, ok)
						exists := azure.ResourceGroupExists(t, resourceGroupName, subscriptionID)
						assert.True(t, exists, "Resource group does not exist")
					})
			})
		}
	}
}
```

Only concern now is that the [azure module](https://github.com/gruntwork-io/terratest/tree/master/modules/azure) uses an expired azure go package (github.com/Azure/go-autorest). The new [go sdk](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/azcore) doesn't have a direct replacement for some of the functionality they are using so I am little uneasy using the module.  Appreciate all the help getting this working!
